[DebuggerStepThrough]
private void InitializeComponent()
{
    this.ComboBox1 = new ComboBox();
    this.Label1 = new Label();
    this.Button1 = new Button();
    this.Label2 = new Label();
    this.TextBox1 = new TextBox();
    this.Label3 = new Label();
    this.Button2 = new Button();
    this.Button3 = new Button();
    base.SuspendLayout();
    this.ComboBox1.BackColor = Color.LightBlue;
    this.ComboBox1.FormattingEnabled = true;
    this.ComboBox1.Location = new Point(12, 0x1a);
    this.ComboBox1.Name = "ComboBox1";
    this.ComboBox1.Size = new Size(0xad, 0x15);
    this.ComboBox1.TabIndex = 0;
    this.Label1.AutoSize = true;
    this.Label1.Location = new Point(12, 9);
    this.Label1.Name = "Label1";
    this.Label1.Size = new Size(0x74, 13);
    this.Label1.TabIndex = 1;
    this.Label1.Text = "Preferred MAC address";
    this.Button1.Location = new Point(11, 0x35);
    this.Button1.Name = "Button1";
    this.Button1.Size = new Size(0xad, 0x2a);
    this.Button1.TabIndex = 2;
    this.Button1.Text = "Generate System Code";
    this.Button1.UseVisualStyleBackColor = true;
    this.Label2.AutoSize = true;
    this.Label2.Location = new Point(12, 0x62);
    this.Label2.Name = "Label2";
    this.Label2.Size = new Size(0x45, 13);
    this.Label2.TabIndex = 3;
    this.Label2.Text = "System Code";
    this.TextBox1.BackColor = Color.PeachPuff;
    this.TextBox1.Location = new Point(12, 0x72);
    this.TextBox1.Name = "TextBox1";
    this.TextBox1.ReadOnly = true;
    this.TextBox1.Size = new Size(0xac, 20);
    this.TextBox1.TabIndex = 4;
    this.Label3.BackColor = Color.LightGreen;
    this.Label3.BorderStyle = BorderStyle.FixedSingle;
    this.Label3.Location = new Point(12, 0x89);
    this.Label3.Name = "Label3";
    this.Label3.Size = new Size(0xac, 0x62);
    this.Label3.TabIndex = 5;
    this.Label3.Text = "NOTE:\r\n\r\nClicking ACCEPT will copy the System Code to the clipboard!\r\n\r\nJust do CTRL+V when writing the Activation Code request e-mail.";
    this.Button2.Location = new Point(190, 0x72);
    this.Button2.Name = "Button2";
    this.Button2.Size = new Size(0x45, 20);
    this.Button2.TabIndex = 6;
    this.Button2.Text = "Accept";
    this.Button2.UseVisualStyleBackColor = true;
    this.Button3.Location = new Point(190, 0x89);
    this.Button3.Name = "Button3";
    this.Button3.Size = new Size(0x45, 20);
    this.Button3.TabIndex = 7;
    this.Button3.Text = "Cancel";
    this.Button3.UseVisualStyleBackColor = true;
    base.AutoScaleDimensions = new SizeF(6f, 13f);
    base.AutoScaleMode = AutoScaleMode.Font;
    base.ClientSize = new Size(0x10b, 0xf4);
    base.Controls.Add(this.Button3);
    base.Controls.Add(this.Button2);
    base.Controls.Add(this.Label3);
    base.Controls.Add(this.TextBox1);
    base.Controls.Add(this.Label2);
    base.Controls.Add(this.Button1);
    base.Controls.Add(this.Label1);
    base.Controls.Add(this.ComboBox1);
    base.FormBorderStyle = FormBorderStyle.FixedToolWindow;
    base.Name = "Form4";
    this.Text = "VMA Simple Spectrum Analyser";
    base.ResumeLayout(false);
    base.PerformLayout();
}
